#include "stm32f4xx.h"                  // Device header

/* 

This programm allows to measure the analog sigal applied to pin PA1 through a POT

A continous automatic conversion is enabled 

The clock frequency = 16 mhz generated by the internal FRC clock

The ADC clock frequency = Fpclk, Fpclk= Sysclk= 16 mhz

The build in 12-bit ADC is used during the test

*/



// enable clock acess to ADC peripheral : APB2

// configrue pin PA1 (connected to ADC channel number 1) as analog input

// 

#define ADC_EN (1<<0)
#define ADC_DIS (0<<0)
#define ADC_CLK_EN (1<<8)
#define ADC_PIN (
#define PA1_PIN_MODE (1<<2)|(1<<3)
#define PORTA_CLK_EN (1<<0)
#define ADC_CLK_SOURCE
#define ADC_INT_EN (1<<5)
#define CONT_CONVER_EN (1<<1)
#define ADC_PRES  (1<<16) |(0<<17)
#define AUTOMATIC_CONV_EN (1<<8)
#define ADC_CHANNEL_EN (1<<0)
#define START_CONV (1<<30)
void ADC_INIT(void);
int val;
float AN_Val ; 
int main (void)
	
{
  
	
	 RCC->AHB1ENR |= PORTA_CLK_EN;
	 GPIOA->MODER |= PA1_PIN_MODE;
	 ADC_INIT();

	
while (1)
	
{
     
     ADC1->CR2 |= START_CONV;
     while(!(ADC1->SR & 0x2)) {}
		 val= ADC1->DR  ;
		 AN_Val= (float) (val * 3)/4096; 

}

}



void ADC_INIT(void)
	
{

		ADC1->CR2 |= ADC_DIS;
	  RCC->APB2ENR |= ADC_CLK_EN ;
	  ADC1->CR1 |= ADC_INT_EN ;
	  ADC1->CR2 |= CONT_CONVER_EN ;
	  ADC1->CR1 |= AUTOMATIC_CONV_EN ;
    ADC1->CR2 |= ADC_EN;
	  ADC1->SQR3 |= ADC_CHANNEL_EN;

}
